import { mkdir, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

/**
 * PITHOS's own CLI (`pithos run`) shells out to a real `pi` binary — this contender
 * does not embed pi-ai as a library the way autobrin-flue's `.flue/app.ts` does. Pi's
 * built-in `azure-openai-responses` provider unconditionally requests
 * `reasoning.encrypted_content` for any reasoning model (confirmed by reading
 * `@earendil-works/pi-ai`'s `dist/providers/azure-openai-responses.js`), which the
 * Kimi K2.6 Azure AI Foundry deployment 400s on (superagent-ai/benchpress#12, PR #19).
 * autobrin-flue works around this with a `kimi-azure` provider that uses the OpenAI
 * Chat Completions transport (`api: 'openai-completions'`) instead. This module ports
 * that same model definition into a Pi extension so PITHOS gets an identical fix,
 * without modifying superagent-ai/PITHOS or superagent-ai/pi.
 *
 * Placement — global (`~/.pi/agent/extensions/`), not project-local — is required,
 * not a style choice:
 *
 * 1. PITHOS's `LocalExecutionBackend` (used by `sandboxMode: "local"`, this contender's
 *    default) runs `pi` with `cwd` set to a fresh `tempfile.TemporaryDirectory()` that
 *    PITHOS itself creates and destroys per stage, entirely inside its own process.
 *    There is no hook for an external caller to place a file inside that directory
 *    before `pi` starts, so a project-local `.pi/extensions/` is unreachable.
 * 2. `HOME` is only left untouched (so `~/.pi/agent/extensions/` resolves normally)
 *    when PITHOS is invoked *without* `--pi-config-dir`. Passing that flag makes
 *    `LocalExecutionBackend` redirect `HOME` to another fresh per-run temp directory
 *    and copies over only `auth.json`/`models.json` — never `extensions/` — which
 *    would make *any* extension (global or otherwise) invisible to `pi`. This
 *    contender never passes `--pi-config-dir`, so the global path stays reachable.
 *
 * Provider id — `azure-openai-responses`, not a fresh `kimi-azure` id — is also
 * required, not a style choice: PITHOS's own CLI (`pithos/cli.py`) gates every run
 * behind `_provider_auth_status(provider, pi_config_dir)`, which only recognizes a
 * fixed, unmodifiable allowlist of provider ids (`_PROVIDER_AUTH_ENV`) when
 * `pi_config_dir` is unset. `azure-openai-responses` is the only entry in that
 * allowlist matching the `AZURE_OPENAI_API_KEY`/`AZURE_OPENAI_BASE_URL` credentials
 * this deployment actually uses, so `pithos run --provider kimi-azure ...` would be
 * rejected with "no Pi auth found for provider" before `pi` ever starts. Since
 * `pi.registerProvider()` replaces the *entire* model list for a given provider id,
 * this extension reads pi-ai's built-in `azure-openai-responses` models
 * (~30 GPT/o1/o3 entries) and re-registers them alongside the Kimi model, so other
 * Azure OpenAI models stay usable through this same globally-installed extension.
 */

export const KIMI_AZURE_PI_MODEL_ID = 'kimi-k2.6';
export const KIMI_AZURE_PI_EXTENSION_FILENAME = 'benchpress-kimi-azure-provider.ts';

// Ported from autobrin-flue's src/modelMetadata.ts (KIMI_AZURE_COST / KIMI_AZURE_CONTEXT_WINDOW).
// https://azure.microsoft.com/en-us/pricing/details/ai-foundry-models/kimi/
const KIMI_AZURE_CONTEXT_WINDOW = 262_144;
const KIMI_AZURE_COST = { input: 0.95, output: 4, cacheRead: 0.16, cacheWrite: 0 };

export function piAgentExtensionsDir(homeDir: string = os.homedir()): string {
  return path.join(homeDir, '.pi', 'agent', 'extensions');
}

/**
 * Renders the Pi extension source. This is plain text as far as benchpress's own
 * build is concerned — it is executed by Pi's `jiti`-based extension loader inside
 * the `pi` process, not by benchpress, so pi-ai/pi-coding-agent are intentionally
 * not benchpress dependencies. `process.env` reads inside the generated source are
 * evaluated when `pi` starts, not when this string is generated, so a rotated
 * `AZURE_OPENAI_API_KEY` is always picked up without regenerating the file.
 */
export function renderKimiAzurePiExtension(): string {
  return `// Auto-generated by superagent-ai/benchpress (src/contenders/pithosKimiAzureExtension.ts).
// Do not edit by hand -- regenerated on every \`pithos\` contender run. Safe to delete;
// it is a no-op without AZURE_OPENAI_API_KEY/AZURE_OPENAI_BASE_URL.
//
// Gives PITHOS a Kimi K2.6 model on Azure that matches autobrin-flue's own
// \`kimi-azure\` provider (.flue/app.ts): OpenAI Chat Completions transport instead of
// Pi's built-in Azure Responses transport, which 400s on this deployment with
// "Encrypted content is not supported with this model" (see
// superagent-ai/benchpress#12, #23). Re-registers pi-ai's built-in
// azure-openai-responses models alongside it (registerProvider replaces the whole
// list for a provider id) so other Azure OpenAI models stay usable.
import type { ExtensionAPI, ProviderModelConfig } from '@earendil-works/pi-coding-agent';
import { getModels } from '@earendil-works/pi-ai';

const KIMI_AZURE_MODEL_ID = '${KIMI_AZURE_PI_MODEL_ID}';
const KIMI_AZURE_CONTEXT_WINDOW = ${KIMI_AZURE_CONTEXT_WINDOW};
const KIMI_AZURE_COST = ${JSON.stringify(KIMI_AZURE_COST)};

export default function (pi: ExtensionAPI) {
  const apiKey = process.env.AZURE_OPENAI_API_KEY;
  const baseUrl = process.env.AZURE_OPENAI_BASE_URL;
  if (!apiKey || !baseUrl) return;

  const builtinModels: ProviderModelConfig[] = getModels('azure-openai-responses').map((model) => ({
    id: model.id,
    name: model.name,
    api: model.api,
    baseUrl: model.baseUrl || undefined,
    reasoning: model.reasoning,
    thinkingLevelMap: model.thinkingLevelMap,
    input: model.input,
    cost: model.cost,
    contextWindow: model.contextWindow,
    maxTokens: model.maxTokens,
    headers: model.headers,
    compat: model.compat,
  }));

  pi.registerProvider('azure-openai-responses', {
    baseUrl,
    apiKey,
    models: [
      ...builtinModels,
      {
        id: KIMI_AZURE_MODEL_ID,
        name: 'Kimi K2.6',
        api: 'openai-completions',
        reasoning: true,
        input: ['text', 'image'],
        cost: KIMI_AZURE_COST,
        contextWindow: KIMI_AZURE_CONTEXT_WINDOW,
        maxTokens: KIMI_AZURE_CONTEXT_WINDOW,
        // Same compat flags as autobrin-flue's kimiAzureModel() (.flue/app.ts). No
        // before_provider_request payload rewrite is needed: with
        // supportsReasoningEffort: false, pi-ai's openai-completions transport never
        // emits a thinking/reasoning_effort field for this model regardless of
        // requested thinking level (verified in dist/providers/openai-completions.js),
        // and PITHOS's own agent.py never requests an explicit "off" thinking level,
        // so autobrin-flue's extra reasoning_effort: 'none' override path never
        // triggers in this integration either.
        compat: {
          supportsStore: false,
          supportsDeveloperRole: false,
          supportsReasoningEffort: false,
          maxTokensField: 'max_tokens',
          supportsStrictMode: false,
        },
      },
    ],
  });
}
`;
}

/**
 * Writes the Kimi Azure Pi extension to the global extensions directory so PITHOS's
 * `pi` subprocess auto-discovers it (see module docs for why this must be global).
 * No-ops (and returns undefined) when Azure Kimi credentials are not configured, so
 * environments not using this feature never get an extension file at all.
 */
export async function ensureKimiAzurePiExtension(options: { env?: NodeJS.ProcessEnv; homeDir?: string } = {}): Promise<string | undefined> {
  const env = options.env ?? process.env;
  if (!env.AZURE_OPENAI_API_KEY || !env.AZURE_OPENAI_BASE_URL) return undefined;

  const dir = piAgentExtensionsDir(options.homeDir);
  const filePath = path.join(dir, KIMI_AZURE_PI_EXTENSION_FILENAME);
  await mkdir(dir, { recursive: true });
  await writeFile(filePath, renderKimiAzurePiExtension(), 'utf8');
  return filePath;
}
